# write a github action to add builds of this go project for linux, windows, and macos to the repository's release page

name: Websocket Utility Release
on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_arch: [amd64, arm64]
        go_os: [linux, windows, darwin]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: GOARCH=${{ matrix.go_arch }} GOOS=${{ matrix.go_os }} go build -o ${{ env.FILENAME }} cmd/websocket-utility/main.go
        env:
          FILENAME: websocket-utility-${{ matrix.go_os }}-${{ matrix.go_arch }}${{ matrix.go_os == 'windows' && '.exe' || '' }}
      - name: Release Binary
        uses: softprops/action-gh-release@v1
        env:
          FILENAME: websocket-utility-${{ matrix.go_os }}-${{ matrix.go_arch }}${{ matrix.go_os == 'windows' && '.exe' || '' }}
        with:
          files: |
            ${{ env.FILENAME }}
  release_html:
    name: Release HTML
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release HTML
        uses: softprops/action-gh-release@v1
        with:
          files: echo.html